spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-wait: 30
      max-active: 8
      max-idle: 8
      min-idle: 0
    timeout: 0

logging:
    level:
      root: debug


