
spring:
  application:
    name: sb
  redis:
    host: 172.21.161.122
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 5000

#
#
#logging:
#  level:
#    root: debug


common:
  rate-limit-redis:
    enabled: true
