
logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 1000000

server:
  port: 8083

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin
#  publisher-confirms: true
  virtual-host: test_vhosts